### PR TITLE
[CU-86epc7upg] feat: coming soon page

### PR DESCRIPTION
**Pull request by mafiefa02**
Add coming soon page before release

### CODE REVIEW

**Comment by mafiefa02** [comment]
bentar mau nyoba tweak animasinya biar ga ngelag

**Comment by mafiefa02** [comment]
dah beres yahh, klo sempet minta tolong review yak @dan9111 @rdanielsn

**Review by rdanielsn — COMMENTED** [review]
punten pip: 
- ada semacam garis perbatasan antar image (gambar terlampir)
- device Win10, browser Chrome v125, zoom 100%
- anehnya klo zoom 80% ga kelihatan :D
- tapi ditest di Android 12: Chrome v125, Firefox v126 hasilnya aman

image

**Comment by rdanielsn** [comment]
bisa jadi karena overlap pip, baru kepikiran

**Comment by mafiefa02** [comment]
> punten pip:
> 
> * ada semacam garis perbatasan antar image (gambar terlampir)
> * device Win10, browser Chrome v125, zoom 100%
> * anehnya klo zoom 80% ga kelihatan :D
> * tapi ditest di Android 12: Chrome v125, Firefox v126 hasilnya aman
> 
> image

harusnya dah fixed yak @rdanielsn

**Review by rdanielsn — DISMISSED** [review]
mantap pip, udah hilang garisnya 🙏🙏

**Review by dan9111 — DISMISSED** [review]

**Comment by mafiefa02** [comment]
Task linked: [CU-86epc7upg Coming soon page](https://app.clickup.com/t/86epc7upg)

**Pull request merged**
